name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev

      - name: Install Python Build Tools
        run: |
          python -m pip install --upgrade pip setuptools wheel cython

      - name: Install SpaCy Separately
        run: python -m pip install spacy==3.8.2 --no-build-isolation

      - name: Install Project Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run Backend Tests
        run: pytest --cov=src/ --cov-report=xml

      - name: Upload Backend Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: backend-coverage-report
          path: coverage.xml
          
