name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Backend Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/bible-ai-backend:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Download Frontend Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: frontend-build
          path: frontend/build

      - name: Generate Deployment Configuration
        run: |
          python deploy/generate_config.py --environment production

      - name: Debug Deployment Environment
        run: |
          echo "DEPLOYMENT_WEBHOOK_URL=${{ secrets.DEPLOYMENT_WEBHOOK_URL }}"
          echo "GITHUB_ACTOR=${{ github.actor }}"

      - name: Deploy to Production Server
        uses: fjogeleit/http-webhook-action@v1
        with:
          url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
          json: |
            {
              "app": "bible-ai",
              "version": "${{ github.sha }}",
              "environment": "production",
              "triggered_by": "${{ github.actor }}"
            }
