name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/bible-ai-backend:latest
            ghcr.io/${{ github.repository }}/bible-ai-backend:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deployment dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Deployment Configuration
        run: python deploy/generate_config.py --environment production

      - name: Deploy to Production
        uses: fjogeleit/http-webhook-action@v1
        with:
          url: ${{ secrets.DEPLOYMENT_WEBHOOK_URL }}
          json: |
            {
              "app": "bible-ai",
              "version": "${{ github.sha }}",
              "environment": "production",
              "triggered_by": "${{ github.actor }}"
            }

      - name: Notify Deployment
        if: success()
        run: |
          echo "Deployment completed successfully"
          # Add notification logic here if needed
