name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']  # Updated Python versions

    steps:
    - uses: actions/checkout@v4  # Updated to v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'  # Enable pip caching
        cache-dependency-path: requirements.txt
    
    - name: Install required system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential libffi-dev libssl-dev
    
    - name: Install PyTorch first
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install --upgrade torch==2.6.0 -f https://download.pytorch.org/whl/cpu.html
    
    - name: Install SpaCy separately
      run: python -m pip install spacy==3.8.2 --no-build-isolation
    
    - name: Install dependencies
      run: |
        python -m pip install pytest pytest-cov
        python -m pip install -r requirements.txt
    
    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=src/ --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        flags: python-${{ matrix.python-version }}
